### ISSUE TITLE
【フロントエンド】未ログイン時のリダイレクト

### ISSUE THREAD

**Issue by batora9** [nakamuraitsuki/maximum_forum#48]
未ログイン（トークンを取得していない）時にスレッドを作成やスレッド内でコメントを投稿をするとログイン画面にリダイレクト（転送）するようにしてみましょう。

**Comment by batora9** [comment]
@Tea-England 
これもう一回実装してほしい！

**Comment by Tealands** [comment]
機能しませんでしたか？

**Comment by batora9** [comment]
動作確認せずにmergeされちゃったからもう一回PR立ててほしい！

**Comment by Tealands** [comment]
わかりました
